// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --- //
// qei //
// --- //

#define qei_wrap_target 0
#define qei_wrap 17
#define qei_pio_version 1

static const uint16_t qei_program_instructions[] = {
            //     .wrap_target
    0xa0a0, //  0: mov    pc, pins
    0x0004, //  1: jmp    4
    0x0006, //  2: jmp    6
    0x0008, //  3: jmp    8
    0xe021, //  4: set    x, 1
    0xa0a0, //  5: mov    pc, pins
    0xe020, //  6: set    x, 0
    0xa0a0, //  7: mov    pc, pins
    0x002d, //  8: jmp    !x, 13
    0xa04a, //  9: mov    y, ~y
    0x008b, // 10: jmp    y--, 11
    0xa04a, // 11: mov    y, ~y
    0x000e, // 12: jmp    14
    0x008e, // 13: jmp    y--, 14
    0xa0c2, // 14: mov    isr, y
    0x8000, // 15: push   noblock
    0x2020, // 16: wait   0 pin, 0
    0x2021, // 17: wait   0 pin, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program qei_program = {
    .instructions = qei_program_instructions,
    .length = 18,
    .origin = 0,
    .pio_version = qei_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config qei_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + qei_wrap_target, offset + qei_wrap);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
    return c;
}

// Helper function (for use in C program) to initialize this PIO program
static inline void pio_qei_init(PIO pio, uint sm, uint offset, uint pin, float div){
	pio_sm_config c = qei_program_get_default_config(offset);
	}
// Helper function (for use in C program) to initialize this PIO program
void qei_init(PIO pio, uint sm, uint offset, uint pin, float div) {
    // Sets up state machine and wrap target. This function is automatically
    // generated in blink.pio.h.
    pio_sm_config c = qei_program_get_default_config(offset);
    // Allow PIO to control GPIO pin (as output)
    //pio_gpio_init(pio, pin); //for input unnecessary
    // Connect pin to SET pin (control with 'set' instruction)
    //sm_config_set_set_pins(&c, pin, 2);
    // Set the pin direction to output (in PIO)
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 2, false);
    // Set the clock divider for the state machine
    sm_config_set_clkdiv(&c, div);
    // Load configuration and jump to start of the program
    pio_sm_init(pio, sm, offset, &c);
}

#endif

