// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// pio_qei //
// ------- //

#define pio_qei_wrap_target 0
#define pio_qei_wrap 15
#define pio_qei_pio_version 1

static const uint16_t pio_qei_program_instructions[] = {
            //     .wrap_target
    0xa0a0, //  0: mov    pc, pins
    0x0003, //  1: jmp    3
    0x0005, //  2: jmp    5
    0xe021, //  3: set    x, 1
    0xa0a0, //  4: mov    pc, pins
    0xe020, //  5: set    x, 0
    0xa04a, //  6: mov    y, ~y
    0x0088, //  7: jmp    y--, 8
    0xa04a, //  8: mov    y, ~y
    0x000a, //  9: jmp    10
    0x008b, // 10: jmp    y--, 11
    0x000c, // 11: jmp    12
    0x4040, // 12: in     y, 32
    0x2020, // 13: wait   0 pin, 0
    0x2021, // 14: wait   0 pin, 1
    0x0000, // 15: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_qei_program = {
    .instructions = pio_qei_program_instructions,
    .length = 16,
    .origin = -1,
    .pio_version = pio_qei_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pio_qei_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_qei_wrap_target, offset + pio_qei_wrap);
    return c;
}

static inline void pio_qei_init(PIO pio, uint sm, uint offset, uint pin){
	pio_sm_config c = pio_qei_get_default_config(offset);
}

#endif

